services:
  - type: web
    name: ase-activity-tracker
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /login
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require"
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.lcumwxkwvtalrtxixmip
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
